# CircleCI configuration file

version: 2.1

executors:
    docker-publisher:
        environment:
            IMAGE_NAME: devs32/todolist-springboot
        docker:
            -   image: circleci/buildpack-deps:stretch

dev_branch_only: &dev_branch_only
    filters:
        branches:
            only: develop

prod_branch_only: &prod_branch_only
    filters:
        branches:
            only: master

circle_branch_only: &circle_branch_only
    filters:
        branches:
            only: circleci

jobs:
    build:
        working_directory: ~/repo
        docker:
            -   image: cimg/openjdk:17.0.7
        environment:
            IMAGE_NAME: devs32/todolist-springboot
        steps:
            - checkout
            -   run:
                    name: gradle build
                    command: ./gradlew clean build
            - setup_remote_docker
            -   run:
                    name: docker build
                    command: docker build -t $IMAGE_NAME todolist-web/
            -   run:
                    name: save image
                    command: docker save -o image.tar $IMAGE_NAME
            -   persist_to_workspace:
                    root: .
                    paths:
                        - ./image.tar
    push:
        executor: docker-publisher
        steps:
            -   attach_workspace:
                    at: /tmp/workspace
            - setup_remote_docker
            -   run:
                    name: load image
                    command: docker load -i /tmp/workspace/image.tar
            -   run:
                    name: docker hub login
                    command: docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            -   run:
                    name: docker hub push
                    command: docker push $IMAGE_NAME:latest
    run via ssh:
        machine:
            enabled: true
        steps:
            -   run:
                    name: Add SSH host to known
                    command: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
            -   run:
                    name: connect ssh and run Tes
                    command: ssh -v $SSH_USER@$SSH_HOST -p $SSH_PORT /devs32/todolist/script/deploy.sh

workflows:
    test-pipeline:
        jobs:
            -   build:
                    <<: *circle_branch_only
            -   push:
                    requires:
                        - build
                    <<: *circle_branch_only
            -   run via ssh:
                    requires:
                        - push
                    <<: *circle_branch_only
