# CircleCI configuration file

version: 2.1

dev_branch_only: &dev_branch_only
    filters:
        branches:
            only: develop

prod_branch_only: &prod_branch_only
    filters:
        branches:
            only: production

jobs:
    springboot:
        working_directory: ~/repo
        resource_class: medium
        docker:
            -   image: cimg/openjdk:17.0.7
        steps:
            - checkout
            -   run:
                    name: build
                    command: ./gradlew build
            -   run:
                    name: docker login
                    command: docker login -u devs32 -p dckr_pat_Gs5bC_1QKqP1TN33s6lo63zb-HQ
            -   run:
                    name: push docker images
                    command: docker-compose push

workflows:
    dev-pipeline:
        jobs:
            -   springboot:
                    name: dev-build
                    <<: *dev_branch_only
