# CircleCI configuration file

version: 2.1

dev_branch_only: &dev_branch_only
    filters:
        branches:
            only: develop

prod_branch_only: &prod_branch_only
    filters:
        branches:
            only: master

circle_branch_only: &circle_branch_only
    filters:
        branches:
            only: circleci

jobs:
    build:
        working_directory: ~/repo
        resource_class: medium
        docker:
            - image: cimg/openjdk:17.0.7
        steps:
            - checkout
            -   run:
                    name: gradle build
                    command: ./gradlew clean build
            -   setup_remote_docker
            -   run:
                    name: docker build
                    command: docker build -t devs32/todolist-springboot todolist-web/
    push:
        docker:
            -   image: circleci/buildpack-deps:stretch
        steps:
            -   setup_remote_docker
            -   run:
                    name: docker hub login
                    command: docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            -   run:
                    name: docker hub push
                    command: docker push devs32/todolist-springboot
    run via ssh:
        machine:
            enabled: true
        steps:
            -   run:
                    name: connect ssh
                    command: ssh $SSH_USER@$SSH_HOST -p $SSH_PORT
            -   run:
                    name: test
                    command: ls

workflows:
    test-pipeline:
        jobs:
            - build:
                  <<: *circle_branch_only
            - push:
                  requires:
                      - build
                  <<: *circle_branch_only
            - run via ssh:
                   requires:
                       - build
                       - push
                   <<: *circle_branch_only
