# CircleCI configuration file

version: 2.1

dev_branch_only: &dev_branch_only
    filters:
        branches:
            only: develop

prod_branch_only: &prod_branch_only
    filters:
        branches:
            only: master

circle_branch_only: &circle_branch_only
    filters:
        branches:
            only: circleci

jobs:
    springboot-build:
        working_directory: ~/repo
        resource_class: medium
        docker:
            - image: cimg/openjdk:17.0.7
        steps:
            - checkout
            -   run:
                    command: ./gradlew build
            -   setup_remote_docker:
                    version: 19.03.13
            - run: docker build /todolist-web/DockerFile --tag devs32/todolist-springboot .
            - run: docker login -u devs32 -p ${DOCKER_PASSWORD}
            - run: docker push devs32/todolist-springboot

workflows:
    dev-pipeline:
        jobs:
           - springboot-build:
                 name: dev-build
                 <<: *dev_branch_only

    test-pipeline:
        jobs:
            - springboot-build:
                  name: test-build
                  <<: *circle_branch_only
