# CircleCI configuration file

version: 2.1

dev_branch_only: &dev_branch_only
    filters:
        branches:
            only: develop

circleci_branch_only: &circleci_branch_only
    filters:
        branches:
            only: feat/circleci

prod_branch_only: &prod_branch_only
    filters:
        branches:
            only: production

jobs:
    springboot:
        working_directory: ~/repo
        resource_class: medium
        docker:
            -   image: cimg/openjdk:17.0.7
        steps:
            - checkout
            -   run:
                    name: build
                    command: ./gradlew build
            -   setup_remote_docker:
                    version: 20.10.14
            -   run:
                    name: docker login
                    command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            -   run:
                    name: build images
                    command: docker build -t todolist-dev -f ~/repo/todolist-web/Dockerfile .
            -   run:
                    name: push docker images
                    command: docker push todolist-dev:latest

workflows:
    dev-pipeline:
        jobs:
            -   springboot:
                    name: dev-build
                    <<: *dev_branch_only
    circleci-pipeline:
        jobs:
            -   springboot:
                    name: circle-build
                    <<: *circleci_branch_only
