# CircleCI configuration file

version: 2.1

dev_branch_only: &dev_branch_only
    filters:
        branches:
            only: develop

prod_branch_only: &prod_branch_only
    filters:
        branches:
            only: master

circle_branch_only: &circle_branch_only
    filters:
        branches:
            only: circleci

jobs:
    build and push:
        working_directory: ~/repo
        resource_class: medium
        docker:
            - image: cimg/openjdk:17.0.7
        steps:
            - checkout
            -   run:
                    command: ./gradlew clean build
            -   setup_remote_docker:
                    version: 19.03.13
            -   run: pwd
            -   run: ls todolist-web/build/libs
            -   run: docker build -t devs32/todolist-springboot todolist-web/
            -   run: docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            -   run: docker push devs32/todolist-springboot
    run via ssh:
        machine:
            enabled: true
        steps:
            -   run:
                    name: Deploy Over SSH
                    command: ssh $SSH_USER@$SSH_HOST "<remote deploy command>"

workflows:
    dev-pipeline:
        jobs:
           - build and push:
                 name: dev-build
                 <<: *dev_branch_only

    test-pipeline:
        jobs:
            - build and push:
                  name: test-build
                  <<: *circle_branch_only
