spring:
    config:
        import: optional:vault://todolist/springboot
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
    #        url: vault
    #        username: vault
    #        password: vault
    cloud:
        vault:
            uri: http://118.67.129.204:8200
            authentication: APPROLE
            app-role:
                role-id: c100bffe-7b8d-c84e-8ef0-583af17cf0cf
                secret-id: 551d75c1-e23f-8444-d9c4-a0c75de9002a
                role: todolist
jwt:
    header: Authorization
    secret: ZGV2czMyLXRvZG9saXN0LXNlY3JldC1rZXkmZGV2czMyLXRvZG9saXN0LXNlY3JldC1rZXkmZGV2czMyLXRvZG9saXN0LXNlY3JldC1rZXk=
    accessToken-validity-in-seconds: 3600 # accessToken 유효시간 (1시간)
    refreshToken-validity-in-seconds: 259200 #refreshToken 유효시간 (3일)
logging:
    level:
      kr.co.devs32.todolist: DEBUG
