spring:
    cloud:
        vault:
            uri: http://jparangdev.asuscomm.com:20003
            authentication: APPROLE
            app-role:
                role-id: 2f6e47e1-8c7b-e3b0-b243-86e34674b7a2
                secret-id: 72943a7d-b78b-85ff-a721-1e941e271fb8
                role: todolist
            kv:
                enabled: true
                backend: secrets
                profile-separator: '/'
                default-context: todolist/springboot
