spring:
    jpa:
        hibernate:
            ddl-auto: validate
    security:
      oauth2:
        client:
            registration:
              naver:
                 client-id: msibe18JNNFh9L69e4p_
                 client-secret: rZOGbYWOiZ
                 redirect-uri: http://localhost:8080/naver/callback
                 authorization-grant-type: authorization_code
                 scope:
                   - name
                   - email
            provider:
              naver:
                  authorization-uri: https://nid.naver.com/oauth2.0/authorize
                  token-uri: https://nid.naver.com/oauth2.0/token
                  user-info-uri: https://openapi.naver.com/v1/nid/me
                  user-name-attribute: response
jwt:
    issuer: pjhwin1@gmail.com
    secret_key: study-springboot-todolist
    #    header: Authorization
    #    secret: ZGV2czMyLXRvZG9saXN0LXNlY3JldC1rZXkmZGV2czMyLXRvZG9saXN0LXNlY3JldC1rZXkmZGV2czMyLXRvZG9saXN0LXNlY3JldC1rZXk=
    accessToken-validity-in-seconds: 3600 # accessToken 유효시간 (1시간)
    refreshToken-validity-in-seconds: 604800 #refreshToken 유효시간 (7일)
logging:
    level:
        kr.co.devs32.todolist: DEBUG


