spring:
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        defer-datasource-initialization: true
jwt:
    header: Authorization
    #    secret: vault
    accessToken-validity-in-seconds: 3600
    refreshToken-validity-in-seconds: 259200
