FROM openjdk:17

RUN mkdir /workspace/todolist

ADD /home/circleci/repo/todolist-web/build/libs/app.jar app.jar
ADD setenv.sh setenv.sh

EXPOSE 8080

CMD ["/bin/bash", "-c", "source setenv.sh && exec java $JAVA_OPTS -jar app.jar"]
