# CircleCI configuration file

version: 2.1

dev_branch_only: &dev_branch_only
    filters:
        branches:
            only: dev

prod_branch_only: &prod_branch_only
    filters:
        branches:
            only: prod

orbs:
    gradle: circleci/gradle@2.2.0

executors:
    jdk17-executor:
        docker:
            - image: cimg/openjdk:17.0.7
        resource_class: medium

jobs:
    springboot-build:
        working_directory: ~/repo
        resource_class: medium
        docker:
            - image: cimg/openjdk:17.0.7
        steps:
            - checkout
            -   run:
                    command: ./gradlew build

workflows:
    dev-pipeline:
       - springboot-build:
             name: dev-build
             <<: *dev_branch_only
